packages:
  - apps/*
  - packages/*

catalog:
  "@aws-sdk/client-s3": 3.835.0
  prisma: 7.2.0
  "@prisma/adapter-pg": 7.2.0
  "@prisma/client": 7.2.0
  "@upstash/redis": 1.34.9
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - prisma
