on:
  push:

name: Build and Lint
jobs:
  lint:
    name: ESLint style check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run ESLint
        run: bun lint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style(eslint): fixed eslint style format [skip ci]"

  appbuild:
    name: Build apps
    runs-on: ubuntu-latest
    needs: [lint]
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build apps
        run: bun run build:apps --summarize

      - name: Summarize Turborepo Output
        uses: ./packages/actions/src/turboSummary

  packagebuild:
    name: Build packages
    runs-on: ubuntu-latest
    needs: [lint]
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build pacakges
        run: bun run build:packages --summarize

      - name: Summarize Turborepo Output
        uses: ./packages/actions/src/turboSummary
